spring:
  profiles:
    active: dev

---
server:
  port: 6001 # 端口号
spring:
  profiles: dev # 开发环境
  application:
    name: spring-cloud-config-dev-eureka

eureka:
  instance:
    hostname: eureka6001.com # eureka服务端的实例名称
  client:
    register-with-eureka: false # 服务注册,表示不将自己注册到eureka服务中
    fetch-registry: false # 服务发现 表示自己不从eureka服务中的获取注册信息
    service-url:
      #      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # eureka 客户端与服务端的交互地址
      defaultZone: http://eureka6001.com:6001/eureka/ # eureka 客户端与服务端的交互地址
  server:
    enable-self-preservation: false # 禁用自我保护机制
---

server:
  port: 6001 # 端口号
spring:
  profiles: prod # 开发环境
  application:
    name: spring-cloud-config-prod-eureka

eureka:
  instance:
    hostname: eureka6001.com # eureka服务端的实例名称
  client:
    register-with-eureka: false # 服务注册,表示不将自己注册到eureka服务中
    fetch-registry: false # 服务发现 表示自己不从eureka服务中的获取注册信息
    service-url:
      #      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # eureka 客户端与服务端的交互地址
      defaultZone: http://eureka6001.com:6001/eureka/ # eureka 客户端与服务端的交互地址
  server:
    enable-self-preservation: true # 禁用自我保护机制
