spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  application:
    name: spring-cloud-config-dev-provider
  web:
    resources:
      static-locations: classpath:/static/,classpath:/resources/
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.106.70.85:3306/spring_cloud?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    hikari:
      pool-name: DefaultHikariPool
      maximum-pool-size: 12
      connection-timeout: 60000
      minimum-idle: 10
      idle-timeout: 500000
      max-lifetime: 540000
      connection-test-query: SELECT 1
server:
  port: 8080
mybatis:
  type-aliases-package: entities
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true #访问路径会显示为IP地址
---
spring:
  profiles: prod
  application:
    name: spring-cloud-config-prod-provider
  web:
    resources:
      static-locations: classpath:/static/,classpath:/resources/
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.106.70.85:3306/spring_cloud_cluster?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    hikari:
      pool-name: DefaultHikariPool
      maximum-pool-size: 12
      connection-timeout: 60000
      minimum-idle: 10
      idle-timeout: 500000
      max-lifetime: 540000
      connection-test-query: SELECT 1
server:
  port: 8080
mybatis:
  type-aliases-package: entities
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true #访问路径会显示为IP地址